AWSTemplateFormatVersion: 2010-09-09
Description: ' Template for Production DynamoDB Table'
Parameters:
  ApplicationName:
    Description: >-
      This will be set as the value for the "APPLICATION_NAME" tag on all
      supported resources
    Type: String
  HashAttributeName: 
    Type: String
    Description: Name of the Hash key
  HashAttributeType: 
    Type: String
    AllowedValues: 
      - S
      - N
      - B
    Default: "S"
    Description: AttributeType for  Hash key  
  RangeAttributeName: 
    Type: String
    Description: Name of the Range key 
  RangeAttributeType: 
    Type: String
    AllowedValues: 
      - S
      - N
      - B
    Default: "S"  
    Description: AttributeType for the  Range key   
  ReadCapacityUnits: 
    Type: String
    Description: Read ReadCapacity Units
    Default: "5"  
  WriteCapacityUnits: 
    Type: String
    Description: Write Capacity Units
    Default: "5"
Resources:
  DynamoDBTable: 
    Type: "AWS::DynamoDB::Table"
    Properties: 
      KeySchema: 
        - 
          AttributeName: !Ref HashAttributeName
          KeyType: "HASH"
        - 
          AttributeName: !Ref RangeAttributeName
          KeyType: "RANGE"
      AttributeDefinitions: 
        - 
          AttributeName: !Ref HashAttributeName
          AttributeType: "S"
        - 
          AttributeName: !Ref RangeAttributeName
          AttributeType: "S"    
      ProvisionedThroughput: 
        ReadCapacityUnits: !Ref ReadCapacityUnits
        WriteCapacityUnits: !Ref WriteCapacityUnits 
      Tags:
        - Key: ApplicationName
          Value: !Ref ApplicationName   
Outputs:
  TableName:
    Description: Name of the DynamoDB Table
    Value: !Ref DynamoDBTable
  TableArn:
    Description: Arn of the DynamoDB Table
    Value: !GetAtt DynamoDBTable.Arn
